name: Deploy Website to AWS S3 & CloudFront

on:
  push:
    branches:
      - main  # Change this to master if your primary branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Deploy files to S3
      run: |
        aws s3 sync . s3://moiraresumesite.s3-website-us-east-1.amazonaws.com --delete --exclude ".git*" --exclude ".github*"

    - name: Invalidate CloudFront Cache
      run: |
        aws configure set preview.cloudfront true
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
